spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/big_event
        username: root
        password: 12345678

# logging:
#   level:
#     root: INFO
#     com:
#         mingkun:
#             big_event: DEBUG